### ISSUE TITLE
how can I run the second steps

### ISSUE THREAD

**Issue by zhangrc12138** [ZurichNLP/spoken-to-signed-translation#10]
when I run the 
"download_lexicon \
  --name <signsuisse> \
  --directory <path_to_directory>"I got error .What is the signsuisse and path_to_directory meaning?

**Comment by AmitMY** [comment]
signsuisse is a specific dataset, and `path_to_directory` is for you to decide where to store this lexicon.

Did you run:
```bash
download_lexicon \
  --name signsuisse \
  --directory lexicon
```

If so, what error did you get?

**Comment by Mazsy** [comment]
Hi, I have the following error
TypeError: main() missing 2 required positional arguments: 'name' and 'directory'

I run this:
download_lexicon \
  --name signsuisse \
  --directory lexicon

**Comment by AmitMY** [comment]
Please run them in a single command:
```bash
download_lexicon --name signsuisse --directory lexicon
```
(Note how in my original comment, there were `\` to indicate the line is not over)

If you are getting the same error, I will look into it right away.

**Comment by AmitMY** [comment]
I have found the issue, I will fix it

**Comment by AmitMY** [comment]
Please try again now @Mazsy @zhangrc12138

**Comment by zhangrc12138** [comment]
well,something change.It got another error

Traceback (most recent call last):
  File "/usr/local/bin/download_lexicon", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 109, in main
    add_data(data, args.directory)
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 95, in add_data
    for row in tqdm(data):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/spoken_to_signed/download_lexicon.py", line 26, in load_signsuisse
    import sign_language_datasets.datasets.signsuisse as signsuisse
ModuleNotFoundError: No module named 'sign_language_datasets'

how can I get the dataset?

**Comment by Mazsy** [comment]
Hi, thanks for answering, i am very interested in this project, i can't run.
I already have: ' pip install sign-language-datasets downloaded.' 
however I get this error:

`> download_lexicon --name signsuisse --directory lexicon

Traceback (most recent call last):
  File "/usr/local/bin/download_lexicon", line 8, in <module>
    sys.exit(main())
TypeError: main() missing 2 required positional arguments: 'name' and 'directory'`

**Comment by AmitMY** [comment]
You are correct. I apologize sincerely.
I was running everything in my local env, where local installations of all packages exist.

I have created a release for the datasets library, and validated it in this colab:
https://colab.research.google.com/drive/1UtBmfBIhUa2EdLMnWJr0hxAOZelQ50_9?usp=sharing

You can see that it works (just takes a long time, and rather run locally because it downloads a large file for all the poses).

To apply the changes for you locally, please run:
```bash
pip install sign-language-datasets==0.1.8
```

If that doesn't work, I'd recommend rerunning all of the steps, same as in colab

**Comment by Mazsy** [comment]
thanks a million.
